In [1]:
import numpy as np
from numpy import linalg as la

# PCA

### example 1 
<reference> https://www.fun-coding.org/recommend_basic5.html

numpy.random.randint(low, high=None, size=None) 이용 
<br>변수(행)별로 평균을 0으로 centering한 행렬 X′를 만듬 (좌표계의 원점이 평균 벡터와 일치하도록 만듬)

In [2]:
user, item = 5, 3
X = np.random.randint(10, size = (user, item)).astype('float64')
print("* 원본 data")
print(X)
print("* 각 dimension 별 평균")
print(np.mean(X, axis=0))
X -= np.mean(X, axis=0)
print(X)

* 원본 data
[[6. 1. 7.]
 [5. 8. 9.]
 [9. 0. 6.]
 [3. 5. 1.]
 [8. 2. 9.]]
* 각 dimension 별 평균
[6.2 3.2 6.4]
[[-0.2 -2.2  0.6]
 [-1.2  4.8  2.6]
 [ 2.8 -3.2 -0.4]
 [-3.2  1.8 -5.4]
 [ 1.8 -1.2  2.6]]


공분산행렬은 다음 식으로 만들 수 있음
$$Σ=cov(X)= X^T X/(n−1) \propto X^T X $$

In [3]:
C = np.cov(X, rowvar=False)
C

array([[ 5.7 , -5.55,  4.4 ],
       [-5.55, 10.7 , -0.1 ],
       [ 4.4 , -0.1 , 10.8 ]])

공분산행렬을 기반으로 고유값과 고유벡터 구하기

In [4]:
l, principal_axes = la.eig(C)
l, principal_axes

(array([ 0.73408415, 15.80237125, 10.6635446 ]),
 array([[-0.81878304, -0.57401728, -0.00992415],
        [-0.45243256,  0.63451948,  0.62664967],
        [ 0.35341068, -0.51758014,  0.7792379 ]]))

고유값을 높은 순으로 정렬하고, 이에 대응하는 고유벡터와 순서를 맞춤

In [5]:
idx = l.argsort()[::-1]
idx

array([1, 2, 0], dtype=int64)

In [6]:
l, principal_axes = l[idx], principal_axes[:, idx]
l, principal_axes

(array([15.80237125, 10.6635446 ,  0.73408415]),
 array([[-0.57401728, -0.00992415, -0.81878304],
        [ 0.63451948,  0.62664967, -0.45243256],
        [-0.51758014,  0.7792379 ,  0.35341068]]))

In [7]:
np.matmul(principal_axes.T, principal_axes) 

array([[ 1.00000000e+00,  4.81648513e-17,  2.98311285e-17],
       [ 4.81648513e-17,  1.00000000e+00, -5.81539420e-17],
       [ 2.98311285e-17, -5.81539420e-17,  1.00000000e+00]])

차원축소예 (고유값을 기준으로 가장 큰 d개의 고유 벡터 선택)

* principal axis 를 구함

In [8]:
# d = 2 
principal_axes[:, :2]

array([[-0.57401728, -0.00992415],
       [ 0.63451948,  0.62664967],
       [-0.51758014,  0.7792379 ]])

* principal axis 를 기반으로 원본데이터 X에 대한 principal components 를 구함 
  <br>그리고 top 2 개의 components 들에 대해서 dimensionality reduction을 수행

In [9]:
principal_components = X.dot(principal_axes)
principal_components

array([[-1.59168747, -0.90910172,  1.37115465],
       [ 2.38880587,  5.04584594, -0.27026888],
       [-3.43067865, -2.34476173, -0.9861726 ],
       [ 5.77392309, -3.04815795, -0.10269053],
       [-3.14036283,  1.25617545, -0.01202265]])

In [10]:
principal_components_reduced = X.dot(principal_axes[:, :2])
principal_components_reduced

array([[-1.59168747, -0.90910172],
       [ 2.38880587,  5.04584594],
       [-3.43067865, -2.34476173],
       [ 5.77392309, -3.04815795],
       [-3.14036283,  1.25617545]])

In [11]:
# 새로운 변수 z1 과 z2 (5개의 데이터에대한 각각의 dimension component를 갖고있는 vector)
z1 = principal_components_reduced[:,0]
z2 = principal_components_reduced[:,1]
print(z1)
print(z2)

[-1.59168747  2.38880587 -3.43067865  5.77392309 -3.14036283]
[-0.90910172  5.04584594 -2.34476173 -3.04815795  1.25617545]


### example 2

In [12]:
n = 4 
d = 2

In [13]:
X = np.array([[0,-2],[3,-3],[2,0],[-1,1]]).astype('float64')
X

array([[ 0., -2.],
       [ 3., -3.],
       [ 2.,  0.],
       [-1.,  1.]])

In [14]:
# 각 row마다 빼진다. 알아서 broadcasting 되어 계산됨
X -= np.mean(X, axis=0)
X

array([[-1., -1.],
       [ 2., -2.],
       [ 1.,  1.],
       [-2.,  2.]])

$$ C =Σ=cov(X)= X^T X/(n−1) $$

In [15]:
C = np.cov(X, rowvar=False)
print(C)
print(C*(n-1))
np.matmul(X.T,X)

[[ 3.33333333 -2.        ]
 [-2.          3.33333333]]
[[10. -6.]
 [-6. 10.]]


array([[10., -6.],
       [-6., 10.]])

In [16]:
l, principal_axes = la.eig(C)
print(l)
print(principal_axes)

[5.33333333 1.33333333]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [17]:
idx = l.argsort()[::-1]
l, principal_axes = l[idx], principal_axes[:, idx]
print(l)
print(principal_axes)

[5.33333333 1.33333333]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [18]:
principal_components = X.dot(principal_axes)
principal_components

array([[-2.22044605e-16, -1.41421356e+00],
       [ 2.82842712e+00, -4.44089210e-16],
       [ 2.22044605e-16,  1.41421356e+00],
       [-2.82842712e+00,  4.44089210e-16]])

# SVD
<reference> 
<br> https://www.fun-coding.org/recommend_basic6.html
<br> https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix
<br> https://twlab.tistory.com/54
$$ R=UΣV^T $$
* note that $RR^T$ 또는 $R^TR$은 symmetric matrix이므로, eigen decomposition이 가능 
* U는 $RR^T$ 즉, $R$의 공분산 행렬의 고유벡터
* V는 $R^TR$ 즉, $R^T$의 공분산 행렬의 고유벡터
* $ΣΣ^T$ 또는 $Σ^TΣ=λ$ 
  따라서, singular value (특이값) $σ = \sqrt{λ}$
    
> approach: 
  $RR^T$ 또는 $R^TR$ 은 symmetric square matrix 이므로 eigen decomposition이 가능하고,
  <br>이것을 이용하여, U, V, λ 를 구한다.

### example

In [19]:
user, item = 5, 3
R = np.random.randint(10, size = (user, item)).astype('float')
# user, item = 4, 2
# R = np.array([[2,3],[1,4],[0,0],[0,0]]).astype('float')
# R = np.array([[1,0,0,0,0],[0,0,2,0,3],[0,0,0,0,0],[0,2,0,0,0]])
print("* 원본 data")
print(R)
# print("* 각 dimension 별 평균")
# print(np.mean(R, axis=0))
# R -= np.mean(R, axis=0)
# print(R)

* 원본 data
[[3. 5. 9.]
 [6. 3. 6.]
 [1. 5. 8.]
 [9. 1. 9.]
 [5. 9. 2.]]


In [20]:
# we now perform singular value decomposition of X
# "economy size" (or "thin") SVD
# U, s, Vt = la.svd(R, full_matrices=True)
U, s, Vt = la.svd(R, full_matrices=False)
V = Vt.T
print(s)
S = np.diag(s)
print(U)
print(V)
print(S)

[21.45220553  7.84463213  6.10447579]
[[-0.48274233 -0.05440993 -0.45081396]
 [-0.41131347  0.13421733  0.23373531]
 [-0.4004903  -0.16692952 -0.62320608]
 [-0.54412941  0.60055596  0.34948361]
 [-0.37591459 -0.76843499  0.48125872]]
[[-0.51711866  0.25979209  0.8155344 ]
 [-0.44645593 -0.8948035   0.00195231]
 [-0.73025023  0.36309059 -0.5787053 ]]
[[21.45220553  0.          0.        ]
 [ 0.          7.84463213  0.        ]
 [ 0.          0.          6.10447579]]


In [21]:
R

array([[3., 5., 9.],
       [6., 3., 6.],
       [1., 5., 8.],
       [9., 1., 9.],
       [5., 9., 2.]])

In [22]:
np.matmul(np.matmul(U, S), V.T)

array([[3., 5., 9.],
       [6., 3., 6.],
       [1., 5., 8.],
       [9., 1., 9.],
       [5., 9., 2.]])

Trancated SVD: 

In [23]:
# d = 2 
np.matmul(np.matmul(U[:,:2], S[:2,:2]), V.T[:2,:])

array([[ 5.24433676,  5.00537273,  7.40741289],
       [ 4.83636978,  2.99721438,  6.82571499],
       [ 4.1025754 ,  5.00742727,  5.79840455],
       [ 7.26012729,  0.99583491, 10.23461813],
       [ 2.60409674,  8.99426443,  3.70013909]])

### numerical 하게 계산해봤다

In [24]:
print(np.matmul(R.T, R))
print(np.matmul(R, R.T))
C1 = np.matmul(R.T, R)
C2 = np.matmul(R, R.T)

[[152.  92. 162.]
 [ 92. 141. 130.]
 [162. 130. 266.]]
[[115.  87. 100. 113.  78.]
 [ 87.  81.  69. 111.  69.]
 [100.  69.  90.  86.  66.]
 [113. 111.  86. 163.  72.]
 [ 78.  69.  66.  72. 110.]]


In [25]:
# # C1 is a symmetric matrix and so it can be diagonalized:
l, principal_axes = la.eig(C1)
# sort results wrt. eigenvalues
idx = l.argsort()[::-1]
l, principal_axes = l[idx], principal_axes[:, idx]
# the eigenvalues in decreasing order
print ("eigenvalues = \n", l)
# a matrix of eigenvectors (each column is an eigenvector)
V = principal_axes
print ("eigenvectors, which is same with V = \n", V)
# principal_components = R.dot(principal_axes)
# print ("principal_components = \n", principal_components)

eigenvalues = 
 [460.19712204  61.53825326  37.2646247 ]
eigenvectors, which is same with V = 
 [[ 0.51711866  0.25979209  0.8155344 ]
 [ 0.44645593 -0.8948035   0.00195231]
 [ 0.73025023  0.36309059 -0.5787053 ]]


In [26]:
singulars = np.sqrt(l)
print(singulars)
U = np.matmul(R, V)
# print(U)
for i, sing in enumerate(singulars):
    U[:,i] = U[:,i]/sing
print(U)

[21.45220553  7.84463213  6.10447579]
[[ 0.48274233 -0.05440993 -0.45081396]
 [ 0.41131347  0.13421733  0.23373531]
 [ 0.4004903  -0.16692952 -0.62320608]
 [ 0.54412941  0.60055596  0.34948361]
 [ 0.37591459 -0.76843499  0.48125872]]


In [27]:
S = np.diag(singulars)
S

array([[21.45220553,  0.        ,  0.        ],
       [ 0.        ,  7.84463213,  0.        ],
       [ 0.        ,  0.        ,  6.10447579]])

In [28]:
R

array([[3., 5., 9.],
       [6., 3., 6.],
       [1., 5., 8.],
       [9., 1., 9.],
       [5., 9., 2.]])

In [29]:
np.matmul(np.matmul(U, S), V.T)

array([[3., 5., 9.],
       [6., 3., 6.],
       [1., 5., 8.],
       [9., 1., 9.],
       [5., 9., 2.]])