In [1]:
import numpy as np
from numpy import linalg as la
import math

reference:
<br> https://darkpgmr.tistory.com/105
<br> https://twlab.tistory.com/46
<br> https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process // Gram–Schmidt_process

In [2]:
# R = np.ones((3,1))
# print(R.shape)
# print(np.size(R, axis=0))
# print(np.size(R, axis=1))
# print(R)
np.set_printoptions(precision=3)

# Q1

In [3]:
M = np.array([[1,1,1],[1,2,3],[1,3,5]]).astype("float")
print(M)

[[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 5.]]


* 모듈을 사용하여 계산해보았다.

In [4]:
l, principal_axes = la.eig(M)
idx = l.argsort()[::-1]
l, principal_axes = l[idx], principal_axes[:, idx]
print(l)
print(principal_axes)

[ 7.162e+00  8.377e-01 -2.958e-16]
[[-0.218 -0.886  0.408]
 [-0.522 -0.248 -0.816]
 [-0.825  0.391  0.408]]


(a)
* power iteration 방법을 사용
<br> $v_{t} = (M/norm(Mv_{t-1}))v_{t-1}$

In [5]:
elipslion = 1e-8
v = np.ones((np.size(M, axis=0),1))
iteration = 0
distance = 100
while distance > elipslion:
    print("iteration", iteration, "...")
    prev_v = v
    Mv = np.matmul(M,v)
    v = Mv/la.norm(Mv, 'fro')
    iteration = iteration + 1
    distance = np.linalg.norm(v-prev_v)
    print("distance = ",np.linalg.norm(v-prev_v))
print(v)

iteration 0 ...
distance =  0.890429726059787
iteration 1 ...
distance =  0.04894577225762312
iteration 2 ...
distance =  0.005731964656124671
iteration 3 ...
distance =  0.0006704398749803433
iteration 4 ...
distance =  7.841675765141245e-05
iteration 5 ...
distance =  9.171868646837906e-06
iteration 6 ...
distance =  1.072770371155959e-06
iteration 7 ...
distance =  1.2547456940108733e-07
iteration 8 ...
distance =  1.4675897058106624e-08
iteration 9 ...
distance =  1.7165387380306382e-09
[[0.218]
 [0.522]
 [0.825]]


(b)

In [6]:
l = np.matmul(np.matmul(v.T, M),v)
print(l)

[[7.162]]


(c)
* eliminate principal eigen vector $M_{new} = M - \lambda v v^T $


In [7]:
M = M - np.matmul(l*v,v.T)
print(M)

[[ 0.658  0.184 -0.291]
 [ 0.184  0.051 -0.081]
 [-0.291 -0.081  0.128]]


(d)
* <br> power iteration 
  <br> then, we can get eigen vector corresponding to 2nd largeset eigen value 

In [8]:
elipslion = 1e-8
v = np.ones((np.size(M, axis=0),1))
iteration = 0
distance = 100
while distance > elipslion:
    print("iteration", iteration, "...")
    prev_v = v
    Mv = np.matmul(M,v)
    v = Mv/la.norm(Mv, 'fro')
    iteration = iteration + 1
    distance = np.linalg.norm(v-prev_v)
#     print("distance = ",np.linalg.norm(v-prev_v))
print(v)

iteration 0 ...
iteration 1 ...
[[ 0.886]
 [ 0.248]
 [-0.391]]


In [9]:
l = np.matmul(np.matmul(v.T, M),v)
print(l)

[[0.838]]


# Q2

In [10]:
user, item = 7, 5
M = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2]]).astype('float')
print(M)

[[1. 1. 1. 0. 0.]
 [3. 3. 3. 0. 0.]
 [4. 4. 4. 0. 0.]
 [5. 5. 5. 0. 0.]
 [0. 0. 0. 4. 4.]
 [0. 0. 0. 5. 5.]
 [0. 0. 0. 2. 2.]]


* Compute SVD decomposition
<br>find eigen value and corresponding eigen vectors of $M^TM$
<br>form decreasing order matrix as $V$ and top $k$ eigen values(singular values)list as $s$ 
<br>$RV_i / s_i= U_i$ 
<br> where $U_i, V_i$ be $i$ th column of $U, V$, $i = 1,2, ..., k$  . 

* using module, SVD decomposition can be calculated 

In [11]:
U, s, Vt = la.svd(M, full_matrices=True)
V = Vt.T
print(s)

[12.369  9.487  0.     0.     0.   ]


In [12]:
k = 2
S = np.diag(s[:k])
print(S)
print(U[:,:k])
print(V[:,:k].T)

[[12.369  0.   ]
 [ 0.     9.487]]
[[-0.14   0.   ]
 [-0.42   0.   ]
 [-0.56   0.   ]
 [-0.7    0.   ]
 [ 0.    -0.596]
 [ 0.    -0.745]
 [ 0.    -0.298]]
[[-0.577 -0.577 -0.577 -0.    -0.   ]
 [-0.    -0.    -0.    -0.707 -0.707]]


(a)

* given query $q$, we can map $q$ into concept space by $qV$
<br> reversely, $qVV^T = q$. This is because $VV^T = I$(identitiy matrix).

In [13]:
q = np.array([0,3,0,0,4])
mapped_q = np.matmul(q,V[:,:k]) # discard right part after k th column   
mapped_q 

array([-1.732, -2.828])

(b)

In [14]:
estimated_q = np.matmul(mapped_q,V[:,:k].T)
estimated_q

array([1., 1., 1., 2., 2.])

# Q3

In [15]:
M

array([[1., 1., 1., 0., 0.],
       [3., 3., 3., 0., 0.],
       [4., 4., 4., 0., 0.],
       [5., 5., 5., 0., 0.],
       [0., 0., 0., 4., 4.],
       [0., 0., 0., 5., 5.],
       [0., 0., 0., 2., 2.]])

In [16]:
M_norm = la.norm(M, 'fro')
M_norm**2

243.0

In [17]:
Matrix = M[:,:1]
Matrix_prob = (la.norm(Matrix, 'fro')**2)/M_norm**2
Alien = M[:,1:2]
Alien_prob = (la.norm(Alien, 'fro')**2)/M_norm**2
Star = M[:,2:3]
Star_prob = (la.norm(Star, 'fro')**2)/M_norm**2
Casa = M[:,3:4]
Casa_prob = (la.norm(Casa, 'fro')**2)/M_norm**2
Titanic = M[:,-1:]
Titanic_prob = (la.norm(Titanic, 'fro')**2)/M_norm**2
print(Matrix_prob)
print(Alien_prob)
print(Star_prob)
print(Casa_prob)
print(Titanic_prob)

0.20987654320987656
0.20987654320987656
0.20987654320987656
0.1851851851851852
0.1851851851851852


In [18]:
Joe = M[:1, :]
Joe_prob = (la.norm(Joe, 'fro')**2)/M_norm**2
Jim = M[1:2, :]
Jim_prob = (la.norm(Jim, 'fro')**2)/M_norm**2
John = M[2:3, :]
John_prob = (la.norm(John, 'fro')**2)/M_norm**2
Jack = M[3:4, :]
Jack_prob = (la.norm(Jack, 'fro')**2)/M_norm**2
Jill = M[4:5, :]
Jill_prob = (la.norm(Jill, 'fro')**2)/M_norm**2
Jenny = M[5:6, :]
Jenny_prob = (la.norm(Jenny, 'fro')**2)/M_norm**2
Jane = M[-1:, :]
Jane_prob = (la.norm(Jane, 'fro')**2)/M_norm**2
print(Joe_prob)
print(Jim_prob)
print(John_prob)
print(Jack_prob)
print(Jill_prob)
print(Jenny_prob)
print(Jane_prob)

0.012345679012345677
0.1111111111111111
0.19753086419753083
0.308641975308642
0.13168724279835395
0.20576131687242802
0.03292181069958849


(a)

In [19]:
r = 2
C = np.hstack((Matrix/math.sqrt(2*Matrix_prob), Alien/math.sqrt(2*Alien_prob)))
R =  np.vstack((Jim/math.sqrt(2*Jim_prob), John/math.sqrt(2*John_prob)))
print(C)
print(R)

[[1.543 1.543]
 [4.63  4.63 ]
 [6.174 6.174]
 [7.717 7.717]
 [0.    0.   ]
 [0.    0.   ]
 [0.    0.   ]]
[[6.364 6.364 6.364 0.    0.   ]
 [6.364 6.364 6.364 0.    0.   ]]


In [20]:
W = M[1:3,1:3]
print(W)
X, s, Yt = la.svd(W, full_matrices=True)
S = np.diag(s)
print(S)
print(X)
print(Yt)
# np.reciprocal(S)
S = la.pinv(S) # Moore-Penrose pseudoinverse
S

[[3. 3.]
 [4. 4.]]
[[7.071 0.   ]
 [0.    0.   ]]
[[-0.6 -0.8]
 [-0.8  0.6]]
[[-0.707 -0.707]
 [-0.707  0.707]]


array([[0.141, 0.   ],
       [0.   , 0.   ]])

In [21]:
U = np.matmul(np.matmul(Yt.T, S**2), X.T)
U

array([[0.008, 0.011],
       [0.008, 0.011]])

In [22]:
 np.matmul(np.matmul(C, U), R)

array([[0.389, 0.389, 0.389, 0.   , 0.   ],
       [1.167, 1.167, 1.167, 0.   , 0.   ],
       [1.556, 1.556, 1.556, 0.   , 0.   ],
       [1.945, 1.945, 1.945, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ]])

(b)

In [23]:
C = np.hstack((Alien/math.sqrt(2*Alien_prob), Star/math.sqrt(2*Star_prob)))
R =  np.vstack((Jack/math.sqrt(2*Jack_prob), Jill/math.sqrt(2*Jill_prob)))
print(C)
print(R)

[[1.543 1.543]
 [4.63  4.63 ]
 [6.174 6.174]
 [7.717 7.717]
 [0.    0.   ]
 [0.    0.   ]
 [0.    0.   ]]
[[6.364 6.364 6.364 0.    0.   ]
 [0.    0.    0.    7.794 7.794]]


In [24]:
M[:,[1,2]]
print(M[[3,4],:])
print(M[:,[1,2]])
M[[3,4],:][:,[1,2]]

[[5. 5. 5. 0. 0.]
 [0. 0. 0. 4. 4.]]
[[1. 1.]
 [3. 3.]
 [4. 4.]
 [5. 5.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


array([[5., 5.],
       [0., 0.]])

In [25]:
W = M[[3,4],:][:,[1,2]]
X, s, Yt = la.svd(W, full_matrices=True)
S = np.diag(s)
print(S)
print(X)
print(Yt)
# np.reciprocal(S)
S = la.pinv(S) # Moore-Penrose pseudoinverse
S

[[7.071 0.   ]
 [0.    0.   ]]
[[1. 0.]
 [0. 1.]]
[[ 0.707  0.707]
 [-0.707  0.707]]


array([[0.141, 0.   ],
       [0.   , 0.   ]])

In [26]:
U = np.matmul(np.matmul(Yt.T, S**2), X.T)
np.matmul(np.matmul(C, U), R)

array([[0.278, 0.278, 0.278, 0.   , 0.   ],
       [0.833, 0.833, 0.833, 0.   , 0.   ],
       [1.111, 1.111, 1.111, 0.   , 0.   ],
       [1.389, 1.389, 1.389, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ]])

(c)

In [27]:
C = np.hstack((Matrix/math.sqrt(2*Matrix_prob), Titanic/math.sqrt(2*Titanic_prob)))
R =  np.vstack((Joe/math.sqrt(2*Joe_prob), Jane/math.sqrt(2*Jane_prob)))
print(C)
print(R)

[[1.543 0.   ]
 [4.63  0.   ]
 [6.174 0.   ]
 [7.717 0.   ]
 [0.    6.573]
 [0.    8.216]
 [0.    3.286]]
[[6.364 6.364 6.364 0.    0.   ]
 [0.    0.    0.    7.794 7.794]]


In [28]:
W = M[[0,6],:][:,[0,4]]
X, s, Yt = la.svd(W, full_matrices=True)
S = np.diag(s)
# print(S)
print(X)
print(Yt)
# np.reciprocal(S)
S = la.pinv(S) # Moore-Penrose pseudoinverse
print(S)
U = np.matmul(np.matmul(Yt.T, S**2), X.T)
print(U)

[[0. 1.]
 [1. 0.]]
[[0. 1.]
 [1. 0.]]
[[0.5 0. ]
 [0.  1. ]]
[[1.   0.  ]
 [0.   0.25]]


In [29]:
np.matmul(np.matmul(C, U), R)

array([[ 9.823,  9.823,  9.823,  0.   ,  0.   ],
       [29.468, 29.468, 29.468,  0.   ,  0.   ],
       [39.291, 39.291, 39.291,  0.   ,  0.   ],
       [49.113, 49.113, 49.113,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , 12.807, 12.807],
       [ 0.   ,  0.   ,  0.   , 16.009, 16.009],
       [ 0.   ,  0.   ,  0.   ,  6.404,  6.404]])

test

In [30]:
C = np.hstack((Alien/math.sqrt(2*Alien_prob), Casa/math.sqrt(2*Casa_prob)))
R =  np.vstack((Jenny/math.sqrt(2*Jenny_prob), Jack/math.sqrt(2*Jack_prob)))
print(C)
print(R)

[[1.543 0.   ]
 [4.63  0.   ]
 [6.174 0.   ]
 [7.717 0.   ]
 [0.    6.573]
 [0.    8.216]
 [0.    3.286]]
[[0.    0.    0.    7.794 7.794]
 [6.364 6.364 6.364 0.    0.   ]]


In [31]:
W = M[[5,3],:][:,[1,3]]
X, s, Yt = la.svd(W, full_matrices=True)
S = np.diag(s)
# print(S)
print(X)
print(Yt)
# np.reciprocal(S)
S = la.pinv(S) # Moore-Penrose pseudoinverse
print(S)
U = np.matmul(np.matmul(Yt.T, S**2), X.T)
print(U)

[[ 0. -1.]
 [-1.  0.]]
[[-1. -0.]
 [-0. -1.]]
[[0.2 0. ]
 [0.  0.2]]
[[0.   0.04]
 [0.04 0.  ]]


In [32]:
np.matmul(np.matmul(C, U), R)

array([[0.393, 0.393, 0.393, 0.   , 0.   ],
       [1.179, 1.179, 1.179, 0.   , 0.   ],
       [1.572, 1.572, 1.572, 0.   , 0.   ],
       [1.965, 1.965, 1.965, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 2.049, 2.049],
       [0.   , 0.   , 0.   , 2.561, 2.561],
       [0.   , 0.   , 0.   , 1.025, 1.025]])