# prerequsite
pip install cvxopt


In [1]:
#import matplotlib.pyplot as plt
from cvxopt import matrix, solvers
import numpy

ModuleNotFoundError: No module named 'cvxopt'

In [11]:
import numpy

In [25]:
m = 3 * numpy.ones(3)
m = numpy.diag(m)
print(m)
m[1][1:]

[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


array([3., 0.])